package cipher

import (
	"fmt"
	"gitlab.com/parallelcoin/duo/pkg/buf/bytes"
	"gitlab.com/parallelcoin/duo/pkg/buf/pass"
	"gitlab.com/parallelcoin/duo/pkg/buf/sec"
	"testing"
)

func TestCipher(t *testing.T) {
	s := "testtest"
	a := New()
	b := a.crypt.Rand(48).Buf()
	fmt.Println(b)
	c := a.crypt.Buf()
	fmt.Println(c)
	d := passbuf.New()
	d.FromString(s)
	fmt.Println("fromstring", d)
	fmt.Println("empty pw", New().Password())
	var f *Cipher
	f.Password()
	f.Ciphertext()
	f.IV()
	f.Cipher()
	f.Null()
	g := new(Cipher)
	g.Password()
	g.Ciphertext()
	g.IV()
	g.Cipher()
	g.Null().crypt.Move(bytes.New().Rand(13)).Null()
	h := New().Load(bytes.New().Rand(13).(*bytes.Bytes))
	fmt.Println(h.crypt.Buf())
	fmt.Println(g.IsArmed(), f.IsArmed())
	fmt.Println(g.IsUnlocked(), f.IsUnlocked())
	fmt.Println(a.IsLoaded(), f.IsLoaded(), g.IsLoaded(), h.IsLoaded())
	x := f.Load(bytes.New().Rand(11).(*bytes.Bytes))
	fmt.Println(*x.Cipher().Buf().(*[]byte))
	fmt.Println(x.Cipher())
	x.Cipher().Null().Null()
	fmt.Println(x)
	fmt.Println(*x.SetIV(bytes.New().Rand(12).(*bytes.Bytes)).IV())
	fmt.Println(x.SetIV(bytes.New().Rand(11).(*bytes.Bytes)))
	var z *Cipher
	fmt.Println(z)
	fmt.Println(z.SetError("nothing"))
	var n *Cipher
	fmt.Println("SetIV()", n.SetIV(bytes.New().Rand(12).(*bytes.Bytes)).IV().Buf())
	var m *Cipher
	fmt.Println(m.SetIV(nil).IV())
	fmt.Println(*m.SetRandomIV().IV().Buf().(*[]byte))
	fmt.Println("valid receiver")
	pass := passbuf.New().FromString("abcdef")
	C := New().SetRandomIV().Generate(pass)
	C.Decrypt(bytes.New().Rand(64).(*bytes.Bytes))
	fmt.Println("Generate()", C.String())
	C.Disarm()
	fmt.Println("Disarm()", C.String())
	C.Decrypt(bytes.New().Rand(64).(*bytes.Bytes))
	C.Lock()
	fmt.Println("Lock()", C.String())
	C.Decrypt(bytes.New().Rand(64).(*bytes.Bytes))
	pass = passbuf.New().FromString("abcdef")
	C.Unlock(pass)
	fmt.Println("Unlock()", C.String())
	C.Decrypt(bytes.New().Rand(64).(*bytes.Bytes))
	C.Arm()
	fmt.Println("Arm()", C.String())
	C.Decrypt(bytes.New().Rand(64).(*bytes.Bytes))
	ss := []byte("this is a test")
	fmt.Println("plaintext '" + string(ss) + "'")
	fmt.Println("bytes ", ss)
	bb := C.Encrypt(secbuf.New().Load(&ss).(*secbuf.SecBuf))
	fmt.Println("ciphertext", *bb.Buf().(*[]byte))
	BB := C.Decrypt(bb)
	fmt.Println("recovertext", *BB.Buf().(*[]byte))
	fmt.Println("recover as string '" + string(*BB.Buf().(*[]byte)) + "'")
	C.Lock()
	fmt.Println("Unlock()", C.String())
	var cc *Cipher
	cc.Arm()
	cc = new(Cipher)
	cc.Arm()
	cc.password = passbuf.New().FromString("abcdef")
	cc.Arm()
	cc.Load(bytes.New().Rand(32).(*bytes.Bytes))
	cc.Arm()
	cc.SetIV(&bytes.Bytes{})
	cc.Arm()
	var dd *Cipher
	dd.Lock()
	dd.Generate(passbuf.New().FromString("testing"))
	dd.Generate(nil)
	dd.Encrypt(secbuf.New().Rand(32).(*secbuf.SecBuf))
	dd.Decrypt(bytes.New().Rand(32).(*bytes.Bytes))
	dd = new(Cipher)
	dd.Encrypt(secbuf.New().Rand(32).(*secbuf.SecBuf))
	dd.Decrypt(bytes.New().Rand(32).(*bytes.Bytes))
	var ee *Cipher
	ee = new(Cipher)
	ee.Lock()
	var ff *Cipher
	ff.Unlock(nil)
	ff.Disarm()
	ff = new(Cipher)
	ff.Unlock(nil)
	ff.Generate(passbuf.New().FromString("abcdef"))
	ff.gcm = nil
	ff.Decrypt(bytes.New().Rand(32).(*bytes.Bytes))
	ff.Encrypt(secbuf.New().Rand(32).(*secbuf.SecBuf))
	fffff := []byte{}
	ff.Load(bytes.New().Load(fffff).(*bytes.Bytes))
	ff.Arm()
	Gen(nil, nil, 10000)
	Gen(passbuf.New().FromString("testing!"), nil, 10000)
}
